### ISSUE TITLE
Suggested project: untangle some installation snags

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1799]
After installing on AWS, I note have a couple of sore spots that can cause issues for new users, depending on the underlying OS distribution. The shortlist is stuff with version locks (==, <=) in requirements.txt. This typically causes (or is done because of) interaction issues. One major downside is that we are not taking advantage of the latest development for those packages, e.g. cyvcf2.

- [x] OAuthLib - see e.g. #1127 (blocks Werkzeug, which may be a major issue with Flask at some point)
- [x] Weasyprint (especially its deps Cairo and Pango) e.g. #1207
- [x] cyvcf2 <10 (can be complicated; Cython, numpy, htslib and zlib potential hiccups; e.g. #907.
- [ ] Click
- [ ] pymongo #1754 
- [ ] Integration install with Chanjo and Loqusdb is not well described.
- [ ] Best practice deployments with NGINX etc is not documented.

**Comment by dnil** [comment]
But, at least there is a sample instance on AWS now:
 http://ec2-13-48-84-1.eu-north-1.compute.amazonaws.com:5000
<img width="1593" alt="Screenshot 2020-03-13 at 17 18 15" src="https://user-images.githubusercontent.com/758570/76743482-f7d3b180-6772-11ea-8279-03ed7d033f73.png">

<img width="1482" alt="Screenshot 2020-03-13 at 18 00 41" src="https://user-images.githubusercontent.com/758570/76743518-0ae68180-6773-11ea-99e1-2471aae2856e.png">

Enjoy! I'll post an AMI identifier at some point..

**Comment by northwestwitch** [comment]
This is very cool @dnil !!! 🥇

**Comment by henrikstranneheim** [comment]
Nice!

**Comment by dnil** [comment]
Ok, the AMI is now supposedly public, named scout-browser-4.13.1-py36-mongo423 (ami-01df949c9c28882d4). I'm still a bit uncertain about the regionality of this, but at least available on northern-europe..

**Comment by dnil** [comment]
I think I'll close this for now. Several of the issues have updated or changed, and the docker deployments gotten much cleaner and possible to copy on a fresh install, if one does not want to use them for production for some reason.
