### ISSUE TITLE
Find all the report exported to PDF using Weasyprint and refactor to use PDFKit

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3125]
as in #3122 and #3120

- [x] case delivery report (cases viewa) ---> #3127
- [x] download_hpo_genes (cases views) ---> #3132
- [ ] panel_export (panels views) ---> #3133

So we can remove the Weasyprint dependency
