### ISSUE TITLE
Add more helpful error message when variant frequency parsing fails in `scout.parse.variant.transcript`

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics/scout#4406]
I recently triggered these two logging thingies when tinkering around with our VEP annotations:

https://github.com/Clinical-Genomics/scout/blob/490580bd3bb890b71627b9e9750970094f27168f/scout/parse/variant/transcript.py#L348-L350

It would've been nice if that caught `err` was printed out in the logs.

I can add it, if it's OK.

### TODO:

- [x] Add `LOG.error` or extend warnings.
- [x] Caught `err` should be printed
- [x] The offending `key` should be named in the printed error log
- [ ] Can the exceptions be more specific?

**Comment by northwestwitch** [comment]
> I can add it, if it's OK.

That's be great, thanks! 🥇
