### ISSUE TITLE
Scout meeting 2017-10-18

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#637]
- [x] Report functionality - see issue #147 and #605.

We would like a new flag for rapidly dismissing variants.
This works well in conjunction with a report function. A suggestion would be a report that first exports a "variants-view" list for all pinned/classifed/commented, variants on top, a "variants-view" list with dismissed variants below followed by a looong list of separate static copies of variant pages - possibly somewhat trimmed - for each of the aforementioned touched variants (pin, tag, comment, dismiss).

- [x] Status of list of genes without transcripts.
- [x] Next OMIM update (@moonso => produce new list from OMIM-download, @dnil => check inconsistency & upload new gene according to guide)
- [x] Issue #633 status? => Scout should notify you if you search for a gene that isn't "clinical"
- [x] Documentation on transcript status markings (Canonical, Disease associated "HGMD", HGNC-blue?)
- [x] Issue #594 - keep manual gene symbol filter when clicking "clinical filter"?
- [x] MIP 5.0 update (@b4ckm4n)
- [x] What's next in Scout? https://github.com/Clinical-Genomics/scout/projects/14
- [ ] Order portal update
- [ ] Reruns from the portal: https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=13883
- [x] OMIM, gene set updates

**Comment by b4ckm4n** [comment]
- [ ] Update to MIP 5.0

**Comment by robinandeer** [comment]
Actions:

- [ ] document SVdb merge algorithm @dnil (in Scout or MIP)
- [ ] build in dismiss function into commenting for variants #605 
- [ ] export variants: include every variant, that has been interacted with (will be saved as PDF) => dismissed variants will be listed with relevant information for the dismissal (@dnil)
- [ ] send in list of what to include in the export @henrikstranneheim (CMMS), @dnil (ClinGen)
- [ ] highlight genes without refseq mapped to ensembl transcripts @moonso, post a list genes per panel to Scout group in the mean time
- [ ] Remove "C" = canonical badge in the transcript overview @robinandeer
